version: "3.7"

services:
  app:
    build: 
      context: .
      target: dev
    command: bundle exec rails server -b 0.0.0.0
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/postgres
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000/tcp
    networks:
      - backend
    depends_on:
      - db

  db:
    image: postgres:12.2
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db:

networks:
  backend:
