name: Deploy to AWS ECS Fargate (Staging)

on:
  push:
    branches:
      - 'staging'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: chrislennon/action-aws-cli@v1.1

      - name: Build and push image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          image_name: kiez-retter-backend
          image_tag: staging
          registry: 647713163217.dkr.ecr.eu-central-1.amazonaws.com
          build_extra_args: --build-arg RAILS_MASTER_KEY
        env:
          RAILS_MASTER_KEY: ${{secrets.RAILS_MASTER_KEY}}

      - name: Force new deployment
        run: aws ecs update-service --cluster kiez-retter-backend --service kiezretter-staging --force-new-deployment --region eu-central-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
